### ISSUE TITLE
error saat menjalankan test dengan postgres

### ISSUE THREAD

**Issue by marsha97** [ui/django-sms-engine#28]
```
$ `which django-admin` test --settings=sms_engine.test_settings --pythonpath=. -v 2
/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Creating test database for alias 'default' ('test_sms_engine')...
Got an error creating the test database: database "test_sms_engine" already exists

Type 'yes' if you would like to try deleting the test database 'test_sms_engine', or 'no' to cancel: yes
Destroying old test database for alias 'default' ('test_sms_engine')...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, sms_engine
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
  Applying sms_engine.0001_initial... OK
  Applying sms_engine.0002_backend... OK
System check identified no issues (0 silenced).
test_cached_backend_get (sms_engine.tests.test_cached_backend.BackendTest) ... ok
test_cleanup_sms (sms_engine.tests.test_cleanup.CommandTest) ... Deleted 0 mails created before 2018-12-04 04:36:52.885602
Deleted 1 mails created before 2018-12-04 04:36:52.893990
ok
test_empty_backend_alias (sms_engine.tests.test_send_queued.CommandTest) ... [INFO]2019-01-03 04:36:52 PID 15419: Acquiringlock for sending queued smss at /var/folders/tg/n0857j556qqb9q_j55kf7nwh0000gp/T/sms_engine.lock
[INFO]2019-01-03 04:36:52 PID 15419: Process started, sending 1 sms
[ERROR]2019-01-03 04:36:53 PID 15419: connection already closed
Traceback (most recent call last):
  File "./sms_engine/management/commands/send_queued_sms.py", line 39, in handle
    _send_bulk(queued_smss, log_level=log_level)
  File "./sms_engine/sms.py", line 142, in _send_bulk
    sms.save()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 903, in _save_table
    forced_update)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 953, in _do_update
    return filtered._update(values) > 0
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 661,in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1191, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed
ERROR
test_failed_deliveries_logging (sms_engine.tests.test_send_queued.CommandTest) ... ERROR
test_send_queued_mail (sms_engine.tests.test_send_queued.CommandTest) ... [INFO]2019-01-03 04:36:53 PID 15419: Acquiring lock for sending queued smss at /var/folders/tg/n0857j556qqb9q_j55kf7nwh0000gp/T/sms_engine.lock
[ERROR]2019-01-03 04:36:53 PID 15419: connection already closed
Traceback (most recent call last):
  File "./sms_engine/management/commands/send_queued_sms.py", line 38, in handle
    while queued_smss:
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 258,in __nonzero__
    return type(self).__bool__(self)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 254,in __bool__
    self._fetch_all()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed
ERROR
test_successful_deliveries_logging (sms_engine.tests.test_send_queued.CommandTest) ... ERROR
test_get_queued_sms_respecting_priority (sms_engine.tests.test_sms.SMSTest) ... ok
test_send_bulk_sms (sms_engine.tests.test_sms.SMSTest) ... ERROR
test_sms_create (sms_engine.tests.test_sms.SMSTest) ... ERROR
test_sms_send (sms_engine.tests.test_sms.SMSTest) ... ERROR
test_dispatch (sms_engine.tests.test_models.ModelsTest) ... ok
test_backend_cache_busting (sms_engine.tests.test_backends.BackendTest) ... ok
test_dynamic_backends_with_kwargs (sms_engine.tests.test_backends.BackendTest) ... ok
test_email_backend (sms_engine.tests.test_backends.BackendTest) ... ok
test_email_backend_settings (sms_engine.tests.test_backends.BackendTest) ... ok
test_flatten_backends (sms_engine.tests.test_backends.BackendTest) ... ok

======================================================================
ERROR: test_empty_backend_alias (sms_engine.tests.test_send_queued.CommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sms_engine/tests/test_send_queued.py", line 77, in test_empty_backend_alias
    call_command('send_queued_sms', log_level=0)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/core/management/base.py", line330, in execute
    output = self.handle(*args, **options)
  File "./sms_engine/management/commands/send_queued_sms.py", line 39, in handle
    _send_bulk(queued_smss, log_level=log_level)
  File "./sms_engine/sms.py", line 142, in _send_bulk
    sms.save()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 903, in _save_table
    forced_update)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 953, in _do_update
    return filtered._update(values) > 0
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 661,in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1191, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

======================================================================
ERROR: test_failed_deliveries_logging (sms_engine.tests.test_send_queued.CommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sms_engine/tests/test_send_queued.py", line 57, in test_failed_deliveries_logging
    backend_alias='error')
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 393,in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    with self.connection.cursor() as cursor:
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

======================================================================
ERROR: test_send_queued_mail (sms_engine.tests.test_send_queued.CommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sms_engine/tests/test_send_queued.py", line 14, in test_send_queued_mail
    call_command('send_queued_sms')
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/core/management/base.py", line330, in execute
    output = self.handle(*args, **options)
  File "./sms_engine/management/commands/send_queued_sms.py", line 38, in handle
    while queued_smss:
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 258,in __nonzero__
    return type(self).__bool__(self)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 254,in __bool__
    self._fetch_all()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

======================================================================
ERROR: test_successful_deliveries_logging (sms_engine.tests.test_send_queued.CommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sms_engine/tests/test_send_queued.py", line 38, in test_successful_deliveries_logging
    backend_alias='dummy')
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 393,in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    with self.connection.cursor() as cursor:
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

======================================================================
ERROR: test_send_bulk_sms (sms_engine.tests.test_sms.SMSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sms_engine/tests/test_sms.py", line 60, in test_send_bulk_sms
    _send_bulk(SMS.objects.all(), log_level=2)
  File "./sms_engine/sms.py", line 119, in _send_bulk
    sms_count = len(smss)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 232,in __len__
    self._fetch_all()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

======================================================================
ERROR: test_sms_create (sms_engine.tests.test_sms.SMSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sms_engine/tests/test_sms.py", line 18, in test_sms_create
    create_sms(to="+62800000000001", message="Test", backend='dummy')
  File "./sms_engine/sms.py", line 36, in create
    sms.save()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    with self.connection.cursor() as cursor:
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

======================================================================
ERROR: test_sms_send (sms_engine.tests.test_sms.SMSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "./sms_engine/tests/test_sms.py", line 35, in test_sms_send
    send_sms(to="+62800000000001", message="Test Send", backend='dummy')
  File "./sms_engine/sms.py", line 53, in send
    priority, commit, backend)
  File "./sms_engine/sms.py", line 36, in create
    sms.save()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    with self.connection.cursor() as cursor:
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/marsha/code/.virtualenvs/django-sms-engine/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
    cursor = self.connection.cursor()
InterfaceError: connection already closed

----------------------------------------------------------------------
Ran 16 tests in 0.380s

FAILED (errors=7)
Destroying test database for alias 'default' ('test_sms_engine')...
```

**Comment by marsha97** [comment]
tepatnya di `test_send_queued` sama `test_sms`
